"""change tmplink to draft_hash

Revision ID: 87e4a100afc1
Revises: c4098caf6fbd
Create Date: 2024-02-15 21:48:30.911904

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "87e4a100afc1"
down_revision: str | None = "c4098caf6fbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("drafts", "tmplink", new_column_name="draft_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("drafts", "draft_hash", new_column_name="tmplink")
    # ### end Alembic commands ###
