"""add is_published and make draft_id in posts unique

Revision ID: 0a861abcff7d
Revises: a039da76d57d
Create Date: 2024-02-16 17:28:16.387650

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0a861abcff7d"
down_revision: str | None = "a039da76d57d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drafts", sa.Column("is_published", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "posts", ["draft_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_draft_id_key', "posts", type_="unique")
    op.drop_column("drafts", "is_published")
    # ### end Alembic commands ###
